### ISSUE TITLE
Add support for raising a different error after certain retries

### ISSUE THREAD

**Issue by DanielNoord** [channable/opnieuw#30]
It comes up quite often that we retry on a certain internal server error of a party we connect with. We would like to do some retries on it, but at some point we need to give up. Very often there is not much we can do and it would be nice to tell this to our users.

By creating something like `RetryException(raise_if_exhausted=PlatformInternalError)` we can raise an error with a user message after all our retries go through. This would reduce Sentry spam and allow us to give more useful feedback to our customers.

**Comment by jochemb** [comment]
I might not understand the use case. In what way is this different from directly raising and retrying on `PlatformInternalError`?

**Comment by DanielNoord** [comment]
That's a good point :sweat_smile:
