### ISSUE TITLE
Add support to custom functions instead of exceptions

### ISSUE THREAD

**Issue by iurisilvio** [channable/opnieuw#32]
I'd like to retry only for some cases of the exception.

Example, I have to retry when SQLAlchemy fails with lock timeout or statement timeout.

I can raise custom exceptions, but it is not useful for anything else.

```python
@retry(...)
def foo():
    try:
        something
    except sqlalchemy.exc.OperationalError as ex:
        if "lock timeout" in ex.orig.diag.message_primary:
            # RETRY
        if "statement timeout" in ex.orig.diag.message_primary:
            # RETRY
        raise
```

I'd like to extract this logic to make code reusable:

```python
def should_retry(exc):
    return (
        isinstance(exc, sqlalchemy.exc.OperationalError)
        and (
            "lock timeout" in exc.orig.diag.message_primary
            or "statement timeout" in exc.orig.diag.message_primary
        )
    )
    
@retry(retry_on_exceptions=should_retry)
def foo():
    something
```

Maybe I can make it per exception:

```python
def should_retry(exc):
    return (
        "lock timeout" in exc.orig.diag.message_primary
        or "statement timeout" in exc.orig.diag.message_primary
    )
    
@retry(
    retry_on_exceptions=[
        (sqlalchemy.exc.OperationalError, should_retry),
    ],
)
def foo():
    something
```

**Comment by LeonardBesson** [comment]
Thank you for the issue. With opnieuw our approach is to keep things simple and as a result we carefully review introducing new functionalities. 
In this case, increasing the complexity of the interface doesn't seem worth it. We designed the library to focus on exceptions and introduced the builtin `RetryException` to allow for custom fine-grained retry logic. The caller can already encapsulate the desired logic in the following way:

```python
def should_retry(exc: sqlalchemy.exc.OperationalError) -> bool:
    return (
        "lock timeout" in exc.orig.diag.message_primary
        or "statement timeout" in exc.orig.diag.message_primary
    )

@retry(...)
def foo():
    try:
        something()
    except sqlalchemy.exc.OperationalError as ex:
        if should_retry(ex):
            raise RetryException
        raise
```

This favors explicitness and avoids indirect while being slightly more verbose.
